name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."

      - name: Install Angular CLI and dependencies
        run: |
          npm install -g @angular/cli
          npm install

      - name: Run npm audit
        run: npm audit || true
      
      - name: Display audit results
        run: echo "Audit results displayed directly on console"
      
      - name: Lint Angular application
        run: ng lint

      - name: Run unit tests
        run: ng test --watch=false || true

      - name: Build Angular application
        run: ng build --configuration=production
  
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@main
        with:
          project_id: devops-project-420111
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure docker for GCP
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: gcr.io/devops-project-420111/property-app:v1
          build-args: |
            HTTP_PORT=4200

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          image: gcr.io/devops-project-420111/property-app:v1
          service: property-app
          region:  asia-southeast1
          platform: managed
          allow-unauthenticated: true
          env_vars: |
              FOO=bar
              ZIP=zap
        
